[default]
extend-ignore-re = [
    "\\b[A-Z]{2,}\\b",
    "\\b[a-z]+_[a-z]+\\b"
]

[default.extend-words]
crate = "crate"
astro = "astro"

[files]
extend-exclude = [
    "pnpm-lock.yaml",
    "node_modules/**",
    ".pnpm-store/**",
    "dist/**",
    ".next/**",
    ".astro/**",
    "build/**",
    "public/**",
    "package.json",
    "tsconfig.json",
    "README.md"
]